name: flutter_pedometer
description: A Pedometer and Step Detection package for Android and iOS. Step count is streamed as the platform updates it.
version: 1.0.0
homepage: https://github.com/mishatron/flutter_pedometer

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.synteq.flutter_pedometer
        pluginClass: FlutterPedometerPlugin
      ios:
        pluginClass: FlutterPedometerPlugin
